name: Kyani
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4143495294265449
title: 'Kyäni, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07060c'
    - '#ffffff'
    - '#938179'
    - '#0084af'
    - '#00db9d'
  brandStrength: 0.1606354466639459
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
